modified main.js
Eliseev88/courses pull request #1
Opened 2020-08-22 11:25 UTC by Eliseev88

Добавил класс корзины. Написал функцию подсчета общей стоимости товаров в корзине.  С помощью JSON.stringify создал джейсон файл и залил его на гит. Далее с гита тяну через fetch тяну этот файл и парсю его, получаю данные и формирую из них массив товаров. Единственная проблема, что для рендера пришлось установить setTimeout  в 200 мс и то бывает что не всегда успевает загрузиться. Потом навесил слушатель событий клик на весь container и по target'у получаю какой именно товар хотим добавить.

2020-08-23 21:08 UTC, Eliseev88 commented
Сделал еще небольшую программу по подсчету бургера. Украсил ее немного css'oм получилось забавно )))

2020-08-24 13:20 UTC, Om1X requested changes

2020-08-24 13:20 UTC, Om1X commented on project/js/main.js
> +    setTimeout(() => {
вот это грубо и не гарантирует 100% результата. Что если запрос будет идти 5 секунд при медленном интернете? Мы как раз сегодня будем рассматривать работу с асинхронным кодом.

2020-08-24 13:20 UTC, Om1X commented on hamburger/app.js
> +        let local = array.reduce((acc, currentValue) =>
можно сразу return array.reduce();

2020-08-24 13:20 UTC, Om1X commented on hamburger/app.js
> +        return local;
здесь тоже

2020-08-24 13:20 UTC, Om1X commented on hamburger/app.js
> +        return local;
и здесь

2020-08-27 09:34 UTC, merged